# .github/release.yml
changelog:
  # Exclude certain labels from release notes
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - invalid
      - question
      - wontfix
  
  # Categorize changes automatically
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement
        - feat
    
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - hotfix
        - bugfix
    
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    
    - title: 🔧 Maintenance
      labels:
        - chore
        - refactor
        - style
        - ci
        - build
    
    - title: 🔒 Security
      labels:
        - security
    
    - title: ⚡ Performance
      labels:
        - performance
        - perf
    
    - title: 🎨 UI/UX
      labels:
        - ui
        - ux
        - design
    
    - title: 📦 Dependencies
      labels:
        - dependencies
        - deps
    
    - title: Other Changes
      # This will catch any PRs that don't match the above categories