
name: PR Release Notes

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AI preview
        id: generate
        run: |
          # Generate release notes using the GitHub CLI based on the PR's head commit SHA.
          NOTES=$(gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ github.event.pull_request.head.sha }}" \
            --jq '.body')
          
          # Post-process the output:
          # 1. Remove any substring that starts with " in " followed by an http(s) URL.
          # 2. Remove any occurrence of " by @username".
          # 3. Remove duplicate "## What's Changed" header lines.
          SUMMARIZED=$(echo "$NOTES" | \
            sed -E 's/[[:space:]]*in[[:space:]]+https?:\/\/[^ ]+//g' | \
            sed -E 's/ by @[A-Za-z0-9_-]+//g' | \
            grep -v "^## What's Changed")
          
          # Save the summarized notes to a file.
          echo "$SUMMARIZED" > /tmp/release_notes.md
          
          # Create the preview comment.
          cat > /tmp/comment.md << 'EOF'
          ## 🤖 Release Notes Preview
          
          ## What's Changed
          EOF
          cat /tmp/release_notes.md >> /tmp/comment.md
          cat >> /tmp/comment.md << 'EOF'
          
          ---
          *Preview of how this PR will appear in release notes*
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
