name: PR Release Notes

on:
  pull_request:
    types: [opened]
    branches: [main, dev]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AI preview
        id: generate
        run: |
          # Generate release notes using GitHub CLI without using tags.
          # Here we use the PR's head commit SHA as a placeholder.
          NOTES=$(gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ github.event.pull_request.head.sha }}" \
            -f configuration_file_path=".github/release.yml" \
            --jq '.body')
          
          # Save notes to a file.
          echo "$NOTES" > /tmp/release_notes.md
          
          # Create preview comment.
          cat > /tmp/comment.md << 'EOF'
          ## 🤖 Release Notes Preview
          
          EOF
          cat /tmp/release_notes.md >> /tmp/comment.md
          cat >> /tmp/comment.md << 'EOF'
          
          ---
          *Preview of how this PR will appear in release notes*
          EOF
        env:
           GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/comment.md
        env:
           GH_TOKEN: ${{ secrets.GH_PAT }}