name: PR AI Release Notes
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-pr-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for better context
      
      - name: Generate AI Release Notes for PR
        uses: reservamos/ai-release-notes-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Generate notes for commits in this PR
          from-tag: ${{ github.event.pull_request.base.sha }}
          to-tag: ${{ github.event.pull_request.head.sha }}
          # Update PR description with AI summary
          update-pr-description: true
          # Template for PR updates
          template: |
            ## AI-Generated Summary
            
            {release_notes}
            
            ---
            *Auto-generated by AI Release Notes*