name: AI Release Notes on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate Release Notes with AI
        uses: username/ai-release-notes-action@v1  # Replace with actual action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          pr_number: ${{ github.event.pull_request.number }}
          comment_on_pr: true
          update_pr_description: false