name: Generate Release Notes on PR

# Trigger on pull request events
on:
  pull_request:
    types: [opened, closed]
  # Optional: Also trigger manually
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'
        required: true
        default: '1'

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    # Only run if PR is merged or closed
    if: github.event.pull_request.merged == true || github.event.action == 'closed'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: release_notes
          USE_MILESTONE_TITLE: "true"
          FILENAME_PREFIX: Release
          
      - name: Upload Release Notes as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes/*.md
          
      - name: Comment PR with Release Notes (Optional)
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            try {
              const releaseNotesDir = 'release_notes';
              const files = fs.readdirSync(releaseNotesDir);
              const releaseFile = files.find(file => file.endsWith('.md'));
              
              if (releaseFile) {
                const content = fs.readFileSync(path.join(releaseNotesDir, releaseFile), 'utf8');
                
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## Release Notes Generated\n\n${content}`
                });
              }
            } catch (error) {
              console.log('No release notes file found or error reading file:', error);
            }