# .github/workflows/release-drafter.yml
name: Release Drafter (Free)

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}